version: 2.1

# parameters:
#     USERNAME:
#         type: string
#         default: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}


orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
  jq: circleci/jq@2.2.0

workflows:
  basic-test:
    jobs:
      - static-analysis
      - create-push-delete

jobs:

  static-analysis:

    docker:
      - image: circleci/openjdk:latest
    steps:

      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
          
      - checkout
      - restore_cache:
          keys: 
            - pmd-v6.36.0

      - run:
          name: Creating Artifacts folder
          command: |
            mkdir artifacts;
            
      - run:
          name: Install PMD
          command: |
              if [ ! -d pmd-bin-6.36.0 ]; then
                  curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases/6.36.0/pmd-bin-6.36.0.zip" -o pmd-bin-6.36.0.zip
                  unzip pmd-bin-6.36.0.zip
                  rm pmd-bin-6.36.0.zip
              fi
      - save_cache:
          key: pmd-v6.36.0
          paths: 
              - pmd-bin-6.36.0
      - run: 
          name: Run Static Analysis
          command: |
              pmd-bin-6.36.0/bin/run.sh pmd -d . -R ./pmd-ruleset.xml -f html -l apex -r ./artifacts/static-analysis.html
              
              echo "Show the analysis here:"
              echo $(cat ./artifacts/static-analysis.txt)
      - store_artifacts:
          path: ./artifacts/static-analysis.txt


  create-push-delete:

    executor: sfdx/default

    steps:

      - checkout

      - sfdx/install

      - jq/install
    
      - sfdx/auth:
          defaultusername: devhub20210620@prt.com

      # - sfdx/scratch-create:
      #     scratch-alias: << pipeline.parameters.USERNAME >>
      #     scratch-config: ./config/project-scratch-def.json
 
      # - run:
      #     name: Push source
      #     command: >
      #       sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

      # - run:
      #     name: Run tests
      #     command: >
      #       echo $(sfdx force:apex:test:run -l RunLocalTests -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH} -w 30 --json)
      #       echo $TEST_RESULT | jq '.result.outcome'
            
      # - sfdx/scratch-delete:
      #     scratch-alias: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

