version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
workflows:
  basic-test:
    jobs:
      - create-push-delete

jobs:
  create-push-delete:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: devhub20210620@prt.com
      - sfdx/scratch-create:
          scratch-alias: circle_build_$CIRCLE_BUILD_NUM
          # scratch-alias: ${CIRCLE_BRANCH}
          scratch-config: ./config/project-scratch-def.json

      - run:
          command: >
            echo You now have access to the sfdx cli and may execute commands
            against it.

            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM
          name: Run your SFDX commands here


      # - run:
      #   commnd: sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM
      - sfdx/scratch-delete:
          scratch-alias: circle_build_$CIRCLE_BUILD_NUM


# orbs:
#   apex: circleci/salesforce-apex@1.0.1
# version: 2.1
# workflows:
#   deploy_test:
#     jobs:
#       - apex/scratch-deploy-and-test:
#           defaultusername: devhub20210620@prt.com
#           deploydir: ./src
#           permset: ""
#           sampledata-path:
#           scratch-alias: ${CIRCLE_BRANCH}
#           scratch-def: ./config/project-scratch-def.json