version: 2.1

parameters:
    USERNAME:
        type: string
        default: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
  jq: circleci/jq@2.2.0

workflows:
  basic-test:
    jobs:
      - create-push-delete

jobs:
  create-push-delete:

    executor: sfdx/default

    steps:

      - checkout

      - sfdx/install

      - sfdx/auth:
          defaultusername: devhub20210620@prt.com

      - sfdx/scratch-create:
          scratch-alias: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}
          scratch-config: ./config/project-scratch-def.json

      - run:
          command: echo $(<< pipeline.parameters.USERNAME >>)

      - run:
          command: >
            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}
          name: Push source

      - run:
          command:
            TEST_RESULT=$(echo sfdx force:apex:test:run -l RunLocalTests -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH} -w 30 --json | jq '.result.outcome')
            echo $TEST_RESULT
          name: Run tests

      - sfdx/scratch-delete:
          scratch-alias: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

      - store_test_results:
          path: /tmp/test-reports
