version: 2.1

parameters:
    USERNAME:
        type: string
        default: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
  jq: circleci/jq@2.2.0

workflows:
  basic-test:
    jobs:
      - create-push-delete

jobs:

  create-push-delete:

    executor: sfdx/default

    steps:

      - checkout

      - sfdx/install

      - jq/install

      - run:
          name: Print username
          command: echo "<< pipeline.parameters.USERNAME >>"

      - sfdx/auth:
          defaultusername: devhub20210620@prt.com

      - sfdx/scratch-create:
          scratch-alias: << pipeline.parameters.USERNAME >>
          scratch-config: ./config/project-scratch-def.json


      # - run:
      #     name: Test jq
      #     command: echo $()

      - run:
          command: >
            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}
          name: Push source

      # - run:
      #     name: Test scripts
      #     command: |
      #       echo "This is a test scripts run."
      #       echo "This is another line."
      #       sfdx force:apex:test:run -l RunLocalTests -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH} -w 30 --json

      - run:
          name: Test scripts
          command: |
            RESULTS=sfdx force:apex:test:run -l RunLocalTests -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH} -w 30 --json
            echo $RESULTS

      - run:
          name: Run tests
          command: >
            echo $(sfdx force:apex:test:run -l RunLocalTests -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH} -w 30 --json)
            echo $TEST_RESULT | jq '.result.outcome'
            

      # - sfdx/scratch-delete:
      #     scratch-alias: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

      # - store_test_results:
      #     path: /tmp/test-reports
