version: 2.1

# parameters:
#     USERNAME:
#         type: string
#         default: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

# machine:
#   image: ubuntu-1604:202007-01

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
  jq: circleci/jq@2.2.0
  # extend-java: extend/extend-java@0.0.1
  # openjdk-install: cloudesire/openjdk-install@1.2.3

executors:
  default:
    docker:
      - image: circleci/openjdk:11.0.2-jdk

workflows:
  basic-test:
    jobs:
      - create-push-delete

jobs:

  create-push-delete:


    executor: sfdx/default

    steps:

      - checkout

      - sfdx/install

      - jq/install

      # - run:
      #     name: Install OpenJDK 11
      #     command: |
      #       sudo apt-get update && sudo apt-get install openjdk-11-jdk
      #       sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
      #       sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
      #       java -version

      # - run:
      #   name: Print username
      #   command: echo "<< pipeline.parameters.USERNAME >>"

      # - sfdx/auth:
      #   defaultusername: devhub20210620@prt.com

      - run:
          name: Install PMD
          command: |
              if [ ! -d pmd-bin-6.36.0 ]; then
                  wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.36.0/pmd-bin-6.36.0.zip
                  #curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases/6.36.0/rulesets/java/quickstart.xml.zip" -o pmd-bin-6.36.0.zip
                  unzip pmd-bin-6.36.0.zip
                  rm pmd-bin-6.36.0.zip
              fi
          
      - save_cache:
          key: pmd-v6.36.0
          paths: 
              - pmd-bin-6.36.0
      - run: 
          name: Run Static Analysis
          command: |
              pmd-bin-6.36.0/bin/run.sh pmd -d . -R ./pmd-ruleset.xml -f text -l apex -r static-analysis.txt 
      - store_artifacts:
          path: static-analysis.txt

      # - sfdx/scratch-create:
      #     scratch-alias: << pipeline.parameters.USERNAME >>
      #     scratch-config: ./config/project-scratch-def.json
 

      # - run:
      #     name: Push source
      #     command: >
      #       sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

      # - run:
      #     name: Run tests
      #     command: >
      #       echo $(sfdx force:apex:test:run -l RunLocalTests -u circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH} -w 30 --json)
      #       echo $TEST_RESULT | jq '.result.outcome'
            
      # - sfdx/scratch-delete:
      #     scratch-alias: circle_build_$CIRCLE_BUILD_NUM-${CIRCLE_BRANCH}

