name: CI

on:
  push:
    branches: [ circleci-project-setup ]
  pull_request:
    branches: [ circleci-project-setup ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # - name: 'Create scratch org'
      #   uses: forcedotcom/salesforcedx-actions@master
      #   with:
      #       args: 'force:org:list'

      - name: 'Install Salesforce CLI'
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
            mkdir ~/sfdx
            tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
            echo "$HOME/sfdx/bin" >> $GITHUB_PATH
            ~/sfdx/bin/sfdx version

      - uses: actions/checkout@v2

      - name: 'Create scratch org'
        run: sfdx force:org:list

