name: CI

on:
  push:
    branches: [ circleci-project-setup ]
  pull_request:
    branches: [ circleci-project-setup ]

  workflow_dispatch:

jobs:

  pmd-analyser-check:
      name: PMD Static Code Analysis
      permissions:
        security-events: write
        actions: read
        contents: read
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
            # Incremental diffs require fetch depth to be at 0 to grab the target branch
            fetch-depth: '0'
        - name: Run PMD Analyser
          id: pmd-analysis
          uses: synergy-au/pmd-analyser-action@v2
          with:
            pmd-version: '6.34.0'
            file-path: './force-app'
            rules-path: './pmd-ruleset.xml'
            #error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
            #note-rules: 'ApexDoc'

        - name: Upload results to GitHub
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: pmd-output.sarif
            
        - name: No PMD Errors?
          run: |
            if ${{ steps.pmd-analysis.outputs.error-found }}
            then
              exit 3
            fi

  build:
    runs-on: ubuntu-latest

    steps:

      - name: 'Install Salesforce CLI'
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
            mkdir ~/sfdx
            tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
            echo "$HOME/sfdx/bin" >> $GITHUB_PATH
            ~/sfdx/bin/sfdx version

      - uses: actions/checkout@v2

      - name: Run PMD Analyser
        id: pmd-analysis
        uses: synergy-au/pmd-analyser-action@v2
        with:
          pmd-version: '6.34.0'
          file-path: './src'
          rules-path: './pmd-ruleset.xml'
          #error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
         # note-rules: 'ApexDoc'

      # - name: Upload results to GitHub
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: pmd-output.sarif

      - name: No PMD Errors?
        run: |
          if ${{ steps.pmd-analysis.outputs.error-found }}
          then
            exit 3
          fi

