name: PMD Static Code Analysis
on:
  pull_request:
  push:

jobs:
  pmd-analyser-check:
    name: PMD Static Code Analysis
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'


      - name: Install PMD
        run: |

          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.36.0/pmd-bin-6.36.0.zip
          unzip pmd-bin-6.36.0.zip


      - name: Run PMD rules
          pmd-bin-6.36.0/bin/run.sh pmd -d force-app/** -R pmd-ruleset.xml -failOnViolation false -f sarif > pmd-raw-output.json
          
          
      - name: Show files
        run: |
          echo "Plese show some files."
          echo "$(ls)"
          echo $(ls)

      - name: Show json file
        run: |
          echo $(cat pmd-raw-output.json)

          echo "`jq '.base_config[0].value="Alpha-21"' config.json `"

          # Loop through each rule and see if an error should be thrown
          echo "::set-output name=error-found::false"
          while read -r rule; do
              RULE="$(echo "$rule" | jq --raw-output '.id')"
              if [[ $RULE && "$ERROR_RULES" == *"$RULE"* ]]; then
                  echo "::set-output name=error-found::true"
                  break
              fi

      # - name: Run PMD Analyser
      #   id: pmd-analysis
      #   uses: synergy-au/pmd-analyser-action@v2
      #   with:
      #     pmd-version: '6.34.0'
      #     file-path: 'force-app/**'
      #     rules-path: 'pmd-ruleset.xml'
      #     error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
      #     note-rules: 'ApexDoc'



        #echo $(cat pmd-raw-output.sarif)


        # done <<< "$(cat pmd-raw-output.sarif | jq --compact-output '.runs[] .tool .driver .rules[]')"
        # # Set the correct file location for the report
        # cat pmd-raw-output.sarif | jq --arg workspace "$WORKSPACE" '(.runs[] .results[] .locations[] .physicalLocation .artifactLocation .uri) |= ltrimstr($workspace)' > pmd-file-locations-output.sarif
        # # Set the rule level configurations for whether they are notes or errors
        # cat pmd-file-locations-output.sarif | jq --arg errors "$ERROR_RULES" '((.runs[] .tool .driver .rules[]) | select(.id==($errors | split(",")[]))) += {"defaultConfiguration": {"level": "error"}}' > pmd-errors-output.sarif
        # cat pmd-errors-output.sarif | jq --arg notes "$NOTE_RULES" '((.runs[] .tool .driver .rules[]) | select(.id==($notes | split(",")[]))) += {"defaultConfiguration": {"level": "note"}}' > pmd-output.sarif

      # - name: Setup JRE
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: '13.0.2'
      #     java-package: jre
      #     architecture: x64

      # - uses: ashkumar-wtc/setup-pmd@v1
      # - name: run-pmd
      #   run: pmd -d ./force-app/** -R pmd-ruleset.xml -f xml --failOnViolation false > report.xml

      # - uses: ashkumar-wtc/setup-pmd@v1
      # - name: run-pmd
      #   run: pmd -d ./force-app -R rulesets/java/quickstart.xml -f xml --failOnViolation false > report.xml


      # - uses: sfdx-actions/setup-pmd@v1
      # - name: run-pmd
      #   run: pmd -d ./force-app/** -R pmd-ruleset.xml -f xml --failOnViolation false > report.xml

        # run: echo $(pmd -d ./force-app -R rulesets/java/quickstart.xml -f json)

      # - name: Run PMD Analyser
      #   id: pmd-analysis
      #   uses: synergy-au/pmd-analyser-action@v2
      #   with:
      #     pmd-version: '6.34.0'
      #     file-path: './force-app'
      #     rules-path: 'rulesets/java/quickstart.xml'
      #     error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
      #     note-rules: 'ApexDoc'
      
      # - name: Print PMD results
      #   run: |
      #     echo "Printing PMD results"
      #     echo ${{steps.pmd-analysis.outputs.error-found}}
      #     echo ${{steps.pmd-analysis.outputs}}

      # - name: Upload results to GitHub
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: pmd-output.sarif

      # - name: No PMD Errors?
      #   run: |
      #     if ${{ steps.pmd-analysis.outputs.error-found }}
      #     then
      #       exit 3
      #     fi